<form action="<?php echo $this->getFormAction(); ?>" method="post" id="foobar-feedback-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Feedback:') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo $this->__('Name:') ?></label>
                    <div class="input-box">
                        <input name="name" value="<?php echo $this->getName(); ?>" type="text" class="input-text required-entry" id="name" />
                        <?php if ($this->hasError('name')): ?>
                        <div class="validation-advice" id="advice-required-entry-name"><?php echo $this->getError('name'); ?></div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address:') ?></label>
                    <div class="input-box">
                        <input name="email" value="<?php echo $this->getEmail(); ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" id="email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" class="input-text required-entry validate-email" />
                        <?php if ($this->hasError('email')): ?>
                        <div class="validation-advice" id="advice-required-entry-email"><?php echo $this->getError('email'); ?></div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="field">
                    <label for="feedback" class="required"><em>*</em><?php echo $this->__('Feedback:') ?></label>
                    <div class="input-box">
                        <textarea name="feedback" class="input-text required-entry" id="feedback"><?php echo $this->getFeedback(); ?></textarea>
                        <?php if ($this->hasError('feedback')): ?>
                        <div class="validation-advice" id="advice-required-entry-feedback"><?php echo $this->getError('feedback'); ?></div>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <li>
                <?php echo $this->getChildHtml('studioforty9.recaptcha.explicit'); ?>
            </li>
        </ul>
        <div class="buttons-set">
            <p class="back-link"><a href="#" onclick="history.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" class="button"><span><span><?php echo $this->__('Send Feedback') ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var feedbackForm = new VarienForm('foobar-feedback-form', true);
//]]>
</script>
